"""add listened_duration and fix history model

Revision ID: 0f0a3a02c6f6
Revises: d40f18be26bd
Create Date: 2026-05-09 01:00:32.788149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0a3a02c6f6'
down_revision: Union[str, None] = 'd40f18be26bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Таблица user_history удалена из схемы — изменения по ней не применяются.

    with op.batch_alter_table('user_likes', schema=None) as batch_op:
        batch_op.drop_index('ix_user_likes_liked_at')
        batch_op.drop_index('ix_user_likes_track_id')
        batch_op.drop_index('ix_user_likes_user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_likes', schema=None) as batch_op:
        batch_op.create_index('ix_user_likes_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_user_likes_track_id', ['track_id'], unique=False)
        batch_op.create_index('ix_user_likes_liked_at', ['liked_at'], unique=False)

    # ### end Alembic commands ###