"""add is_available to tracks

Revision ID: 9b0eb85f6a46
Revises: ace6932e30d3
Create Date: 2026-05-27 09:43:43.053285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0eb85f6a46'
down_revision: Union[str, None] = 'ace6932e30d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###